name: Sync Wiki Repo

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v4

      - name: Sync from source
        run: |
          git remote add upstream https://github.com/Azka09irgi/ProNighters-Wiki.git
          git fetch upstream
          git reset --hard upstream/main
          git push origin main --force
