name: Sync Wiki Repo

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v3

      - name: Add source repo
        run: |
          git remote add upstream https://github.com/Azka09irgi/ProNighters-Wiki.git
          git fetch upstream

      - name: Merge changes
        run: |
          git merge upstream/main --allow-unrelated-histories -m "Auto sync"

      - name: Push changes
        run: |
          git push origin main
